export class SchoolCalendarDTO{
    id:string;
	name:string;
    yearReference:number;
    startDateSchoolYear:Date;	
	endDateSchoolYear:Date;	
	startDateFirstHalf:Date;	
	endDateFirstHalf:Date;	
	startDateFirstHalfVacation:Date;	
	endDateFirstHalfVacation:Date;	
	startDateSecondHalf:Date;	
	endDateSecondHalf:Date;	
	startDateSecondHalfVacation:Date;	
	endDateSecondHalfVacation:Date;	
	startDateFirstHalfRecess:Date;	
	endDateFirstHalfRecess:Date;	
	startDateSecondHalfRecess:Date;	
	endDateSecondHalfRecess:Date;
}